- name: MongoDB Schema
  when: schema_type == "mongo"
  block:
    - name: Setup MongoDB repo file
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: Install MongoDB Client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed

    - name: Load Schema
      ansible.builtin.shell: mongo --host mongodb-dev.devopsb71.online </app/schema/{{component}}.js

- name: MySQL Schema
  when: schema_type == "mysql"
  block:
    - name: Install MySQL Client
      ansible.builtin.yum:
        name: mysql
        state: installed

    - name: Load Schema
      ansible.builtin.shell: mysql -h mysql-dev.devopsb71.online -uroot -pRoboShop@1, region='us-east-1') }}" < /app/schema/{{component}}.sql